# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZNyzmzXzIwWlvMAfndfiMPkAn29ZbdD

## **Questão 1:** Usabilidade de bibliotecas

Bibliotecas são ferramentas fundamentais na programação, proporcionando funcionalidades prontas para uso, simplificando tarefas complexas e reduzindo o esforço de desenvolvimento. No contexto do processamento de linguagem natural (PLN) para a língua portuguesa, algumas bibliotecas se destacam:

# **1.   spaCy**



*  Ampla gama de funcionalidades, como tokenization, POS tagging, lemmatization e análise de dependências;
*   Suporte para múltiplos idiomas, incluindo português;
*   Vantagem: Rápido e ideal para tarefas de produção;
*   Limitação: Modelos pré-treinados podem não capturar nuances específicas de textos regionais.



# **2.   NLTK**



*  Oferece recursos para stemming, tokenização e processamento de textos mais complexos;
*   Vantagem: Flexível e altamente configurável;
*   Limitação: Geralmente mais lento que spaCy.


# **3.    LanguageTool**

*     Focado na correção gramatical e estilística;
*     Ideal para análise e revisão de textos em português.


# **4.    Gensim e Transformers**

*    Gensim para modelagem de tópicos e embeddings;
*    Transformers para PLN avançado com BERT e GPT.

# **Questão 2:** POS Tagging com spaCy

POS (Part-of-Speech) tagging é o processo de identificar a classe gramatical (substantivo, verbo, adjetivo, etc.) de cada palavra em um texto. No spaCy, isso é feito com modelos pré-treinados que associam tokens às suas categorias gramaticais.
"""

!python -m spacy download pt_core_news_sm

import spacy
import pandas as pd

# Carregando o modelo de português do spaCy
nlp = spacy.load("pt_core_news_sm")

# Texto para análise
texto = "A inteligência artificial está transformando o mundo da tecnologia."

# Processar o texto
doc = nlp(texto)

# Criar uma tabela com tokens e suas respectivas POS tags
dados = {"Token": [token.text for token in doc],
         "POS Tag": [token.pos_ for token in doc],
         "Descrição": [spacy.explain(token.pos_) for token in doc]}

# Converter para DataFrame e exibir
tabela = pd.DataFrame(dados)
print(tabela)

"""# **Questão 3:** Processamento de Texto com Correção, Tokenização, e Stemming/Lematização

(a) Correção Gramatical
Usaremos a biblioteca language_tool_python para corrigir erros em textos.

(b) Tokenização
Usaremos o spaCy para dividir o texto em tokens.

(c) Remoção de Stop Words
Stop words são palavras comuns que podem ser removidas para simplificar a análise textual.

(d) Construção da Tabela
Uma tabela será criada com:

Tokens.
*     Stemming (usando NLTK).
*     Lematização (usando spaCy).
"""

!pip install language_tool_python

import spacy
import language_tool_python
import nltk
import pandas as pd

# Download the 'rslp' resource for NLTK
nltk.download('rslp')

# Configurar spaCy e nltk
nlp = spacy.load("pt_core_news_sm")
stemmer = RSLPStemmer()

# Texto com erros gramaticais
texto_com_erros = "Eu gosto de estuda inteligencia artificial. Ele gostão de aprende tambem."

# (a) Correção gramatical
tool = language_tool_python.LanguageTool('pt-BR')
texto_corrigido = tool.correct(texto_com_erros)
print("Texto Corrigido:", texto_corrigido)

# (b) Tokenizar texto
doc = nlp(texto_corrigido)
tokens = [token.text for token in doc]

# (c) Remover stop words
tokens_filtrados = [token for token in tokens if not nlp.vocab[token].is_stop]

# (d) Tabela com token, stemming e lematização
dados = {
    "Token": tokens_filtrados,
    "Stemming": [stemmer.stem(token) for token in tokens_filtrados],
    "Lematização": [token.lemma_ for token in doc if token.text in tokens_filtrados]
}

tabela_final = pd.DataFrame(dados)
print(tabela_final)