# -*- coding: utf-8 -*-
"""1_positional_encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIG4nZ-nc5otraUMMFVOgngcmJKgujVL
"""

import numpy as np

# Matriz de entrada X
X = np.array([
    [1, 2, 3, 4],
    [4, 3, 2, 1],
    [1, 3, 5, 7],
    [7, 5, 3, 1]
])

# Parâmetros
d_model = X.shape[1]          # Dimensão do vetor (4)
positions = np.arange(X.shape[0])

# Inicializando PE
PE = np.zeros_like(X, dtype=float)

# Calcular os valores da matriz PE
for pos in range(len(positions)):
    for i in range(d_model):
        if i % 2 == 0:  # Índices pares
            PE[pos, i] = np.sin(pos / (10000 ** (i / d_model)))
        else:  # Índices ímpares
            PE[pos, i] = np.cos(pos / (10000 ** ((i - 1) / d_model)))

# Soma de X com PE
X_prime = X + PE

np.set_printoptions(precision=4, suppress=True)

print("Positional Encoding (PE):")
print(PE)

print("\nMatriz Resultante (X + PE):")
print(X_prime)