# -*- coding: utf-8 -*-
"""2_create_Q_K_V.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqY3Ve9BvcDPJdkFKqirnFBPnQV0MQnw
"""

import numpy as np

# 1. Matriz de entrada X
X = np.array([
    [1, 2, 3, 4],
    [4, 3, 2, 1],
    [1, 3, 5, 7],
    [7, 5, 3, 1]
], dtype=float)

print("Matriz X:")
print(X)

# Defina o valor da dimensão do modelo (d_model) a partir da matriz X
# 2. Matrizes de projeção
d_model = X.shape[1]

W_Q = np.eye(d_model)
W_K = np.eye(d_model)
W_V = np.eye(d_model)


# Calcule as matrizes Q, K e V
# **Complete o código para calcular Q, K e V multiplicando X pelas matrizes de pesos**
# 3. Cálculo de Q, K e V
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

# Exibição dos resultados
print("\nMatriz Q (Query):")
print(Q)

print("\nMatriz K (Key):")
print(K)

print("\nMatriz V (Value):")
print(V)

# 4. Scaled Dot-Product Attention
def softmax(matrix):
    exp_matrix = np.exp(matrix - np.max(matrix, axis=1, keepdims=True))
    return exp_matrix / np.sum(exp_matrix, axis=1, keepdims=True)

# Produto QK^T
scores = Q @ K.T
print("\nScores (QK^T):")
print(scores)

# Escalonamento
scaled_scores = scores / np.sqrt(d_model)
print("\nScaled Scores (QK^T / sqrt(d_k)):")
print(scaled_scores)

# Softmax
attention_weights = softmax(scaled_scores)
print("\nPesos de Atenção (Softmax):")
print(attention_weights)

# 5. Saída final da atenção
attention_output = attention_weights @ V
print("\nSaída final da Atenção:")
print(attention_output)