# -*- coding: utf-8 -*-
"""5_multi-head-attention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bz5qL2xP5iD6fRSgP5CRp4uCPKmBhMtm
"""

import numpy as np

class MultiHeadAttention:
    def __init__(self, d_model, num_heads):
        assert d_model % num_heads == 0

        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads

        # Pesos
        self.W_q = np.random.rand(d_model, d_model)
        self.W_k = np.random.rand(d_model, d_model)
        self.W_v = np.random.rand(d_model, d_model)
        self.W_o = np.random.rand(d_model, d_model)

        # Bias
        self.b_q = np.random.rand(d_model)
        self.b_k = np.random.rand(d_model)
        self.b_v = np.random.rand(d_model)
        self.b_o = np.random.rand(d_model)

    def softmax(self, x):
        x = x - np.max(x, axis=-1, keepdims=True)
        exp_x = np.exp(x)
        return exp_x / np.sum(exp_x, axis=-1, keepdims=True)


    def scaled_dot_product_attention(self, Q, K, V):
        # Q, K, V: (batch_size, seq_len, d_k)

        # matmul (correto para batch)
        scores = np.matmul(Q, np.transpose(K, (0, 2, 1)))
        scores = scores / np.sqrt(self.d_k)

        attention_weights = self.softmax(scores)

        output = np.matmul(attention_weights, V)

        return output, attention_weights

    def split_heads(self, X):
        batch_size, seq_len, _ = X.shape
        X = np.reshape(X, (batch_size, seq_len, self.num_heads, self.d_k))
        return np.transpose(X, (0, 2, 1, 3))

    def forward(self, Q, K, V):
        # Projeções lineares
        Q = np.matmul(Q, self.W_q) + self.b_q
        K = np.matmul(K, self.W_k) + self.b_k
        V = np.matmul(V, self.W_v) + self.b_v

        # Split heads
        Q = self.split_heads(Q)
        K = self.split_heads(K)
        V = self.split_heads(V)

        # Atenção por cabeça
        outputs = []
        for h in range(self.num_heads):
            out, _ = self.scaled_dot_product_attention(
                Q[:, h], K[:, h], V[:, h]
            )
            outputs.append(out)

        # Stack heads
        x = np.stack(outputs, axis=1)  # (batch, heads, seq, d_k)

        # Concatenação
        x = np.transpose(x, (0, 2, 1, 3))  # (batch, seq, heads, d_k)
        batch_size, seq_len, _, _ = x.shape
        x = np.reshape(x, (batch_size, seq_len, self.d_model))

        # Projeção final
        output = np.matmul(x, self.W_o) + self.b_o

        return output


# TESTE
if __name__ == "__main__":
    np.random.seed(42)
    np.set_printoptions(precision=4, suppress=True)

    batch_size = 1
    seq_len = 4
    d_model = 6
    num_heads = 3

    Q = np.random.rand(batch_size, seq_len, d_model)
    K = np.random.rand(batch_size, seq_len, d_model)
    V = np.random.rand(batch_size, seq_len, d_model)

    mha = MultiHeadAttention(d_model, num_heads)
    output = mha.forward(Q, K, V)

    print("Saída do Multi-Head Attention:")
    print(output)