# -*- coding: utf-8 -*-
"""7_norm_layer_and_residual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2PU-IEcM73C6-S0Hg5LbvlILwfvxxX1
"""

import numpy as np


def layer_norm(x, eps=1e-6):
    """
    Aplica Layer Normalization na última dimensão do tensor x.
    :param x: Entrada, pode ser um vetor ou uma matriz (última dimensão a ser normalizada).
    :param eps: Valor para evitar divisão por zero.
    :return: x normalizado.
    """
    # Passo 1: Calcular a média ao longo da última dimensão
    mu = np.mean(x, axis=-1, keepdims=True)

    # Passo 2: Calcular a variância ao longo da última dimensão
    sigma = np.var(x, axis=-1, keepdims=True)

    # Passo 3: Normalizar x
    normalized_x = (x - mu) / np.sqrt(sigma + eps)

    return normalized_x


def residual_connection(x, sublayer_output):
    """
    Aplica a conexão residual seguida de Layer Normalization.
    :param x: Entrada original (por exemplo, embedding ou saída de camada anterior).
    :param sublayer_output: Saída do sub-bloco.
    :return: Saída final após a conexão residual e normalização.
    """
    # Passo 1: Somar a entrada com a saída do sub-bloco
    res = x + sublayer_output

    # Passo 2: Aplicar Layer Normalization na soma
    norm_res = layer_norm(res)

    return norm_res


# Exemplo de uso:
if __name__ == "__main__":
    # Exemplo de entrada x (batch_size, features)
    x = np.array([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])

    # Exemplo de saída do sub-bloco (mesma dimensão que x)
    sublayer_out = np.array([[0.5, -0.5, 1.0],
                             [1.0, 0.0, -1.0]])

    # Aplicar a conexão residual com normalização
    output = residual_connection(x, sublayer_out)

    np.set_printoptions(precision=4, suppress=True)
    print("Saída com Residual Connection e Layer Normalization:\n", output)