# -*- coding: utf-8 -*-
"""PROJETO NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSOPjs0I4QUMjil_rzQAgNlu55tMfo-L
"""

import re
import pandas as pd

# =========================================================
# Etapa 1 — Carregamento e exploração
# =========================================================

df = pd.read_csv("dados_sinteticos.csv", encoding="utf-8")

print("Prévia dos dados:")
print(df.head())

print("\nColunas disponíveis:", list(df.columns))
print("\nNúmero total de registros:", len(df))

# =========================================================
# Etapa 2 — Criação de padrões regex
# =========================================================

padroes = {
    "nome": r"[A-ZÁÉÍÓÚÂÊÔÃÕÇa-záéíóúâêôãõç ]{3,}",
    "cpf": r"\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b",
    "cnpj": r"\b\d{2}\.?\d{3}\.?\d{3}/?\d{4}-?\d{2}\b",
    "email": r"[\w\.-]+@[\w\.-]+\.\w+",
    "telefone": r"\(?\d{2}\)?\s?\d{4,5}-?\d{4}",
    "cep": r"\b\d{5}-?\d{3}\b",
    "data": r"\b\d{2}/\d{2}/\d{4}\b",
    "valor": r"R\$ ?\d{1,3}(?:\.\d{3})*,\d{2}"
}

# Teste com o primeiro registro
exemplo = " ".join(df.iloc[0].astype(str))
print("\nTestando regex no primeiro registro:")
for nome, padrao in padroes.items():
    encontrados = re.findall(padrao, exemplo)
    print(f"{nome}: {encontrados}")

# =========================================================
# Etapa 3 — Normalização
# =========================================================

def normaliza_cpf(cpf):
    """Formata CPF como XXX.XXX.XXX-YY"""
    numeros = re.sub(r"\D", "", str(cpf))
    if len(numeros) == 11:
        return f"{numeros[:3]}.{numeros[3:6]}.{numeros[6:9]}-{numeros[9:]}"
    return None

def normaliza_cnpj(cnpj):
    """Formata CNPJ como XX.XXX.XXX/0001-YY"""
    numeros = re.sub(r"\D", "", str(cnpj))
    if len(numeros) == 14:
        return f"{numeros[:2]}.{numeros[2:5]}.{numeros[5:8]}/{numeros[8:12]}-{numeros[12:]}"
    return None

def normaliza_fone(fone):
    """Formata telefone como (XX) 9XXXX-XXXX"""
    numeros = re.sub(r"\D", "", str(fone))
    if len(numeros) == 11:
        return f"({numeros[:2]}) {numeros[2:7]}-{numeros[7:]}"
    elif len(numeros) == 10:
        return f"({numeros[:2]}) {numeros[2:6]}-{numeros[6:]}"
    return None

def normaliza_valor(valor):
    """Converte R$ 1.234,56 -> float"""
    if isinstance(valor, str) and re.search(r"R\$", valor):
        valor = valor.replace("R$", "").replace(".", "").replace(",", ".").strip()
        try:
            return float(valor)
        except:
            return None
    return valor

# Aplicar normalização se as colunas existirem
for col in df.columns:
    if "cpf" in col.lower():
        df["cpf_normalizado"] = df[col].apply(normaliza_cpf)
    if "cnpj" in col.lower():
        df["cnpj_normalizado"] = df[col].apply(normaliza_cnpj)
    if "fone" in col.lower() or "telefone" in col.lower():
        df["telefone_normalizado"] = df[col].apply(normaliza_fone)
    if "valor" in col.lower():
        df["valor_normalizado"] = df[col].apply(normaliza_valor)

# =========================================================
# Etapa 4 — Validação
# =========================================================

def valida_cpf(cpf):
    """Valida CPF (com cálculo dos dígitos verificadores)"""
    if not cpf:
        return False
    cpf = re.sub(r"\D", "", cpf)
    if len(cpf) != 11 or cpf == cpf[0] * 11:
        return False
    for i in range(9, 11):
        soma = sum(int(cpf[num]) * ((i + 1) - num) for num in range(0, i))
        dig = ((soma * 10) % 11) % 10
        if dig != int(cpf[i]):
            return False
    return True

def valida_cnpj(cnpj):
    """Valida CNPJ (cálculo dos dígitos verificadores)"""
    if not cnpj:
        return False
    cnpj = re.sub(r"\D", "", cnpj)
    if len(cnpj) != 14:
        return False
    def calc_dv(cnpj, pesos):
        s = sum(int(a)*b for a,b in zip(cnpj, pesos))
        r = s % 11
        return '0' if r < 2 else str(11 - r)
    dv1 = calc_dv(cnpj[:12], [5,4,3,2,9,8,7,6,5,4,3,2])
    dv2 = calc_dv(cnpj[:12]+dv1, [6,5,4,3,2,9,8,7,6,5,4,3,2])
    return cnpj[-2:] == dv1 + dv2

# Aplicar validações
if "cpf_normalizado" in df.columns:
    df["cpf_valido"] = df["cpf_normalizado"].apply(valida_cpf)
if "cnpj_normalizado" in df.columns:
    df["cnpj_valido"] = df["cnpj_normalizado"].apply(valida_cnpj)

# =========================================================
# Etapa 5 — Relatório
# =========================================================

relatorio = {}

if "cpf_valido" in df.columns:
    total_cpfs = df["cpf_valido"].count()
    validos = df["cpf_valido"].sum()
    relatorio["CPF válidos (%)"] = round(100 * validos / total_cpfs, 2)

if "cnpj_valido" in df.columns:
    total_cnpjs = df["cnpj_valido"].count()
    validos = df["cnpj_valido"].sum()
    relatorio["CNPJ válidos (%)"] = round(100 * validos / total_cnpjs, 2)

relatorio["Total de registros"] = len(df)

# Contagem de campos inconsistentes
inconsistentes = {}
for col in df.columns:
    nulos = df[col].isna().sum()
    inconsistentes[col] = nulos

relatorio_df = pd.DataFrame(list(relatorio.items()), columns=["Métrica", "Valor"])
print("\n===== RELATÓRIO FINAL =====")
print(relatorio_df)

print("\nColunas com inconsistências:")
print(pd.Series(inconsistentes).sort_values(ascending=False).head())

# Exemplo de antes/depois
cols_normalizados = [c for c in df.columns if "normalizado" in c]
if cols_normalizados:
    print("\nExemplo de normalização:")
    print(df[cols_normalizados].head(5))

# Exportar resultado final
df.to_csv("resultados_dados_limpos.csv", index=False, encoding="utf-8-sig")
print("\nArquivo salvo como: resultados_dados_limpos.csv ✅")